name: client-ci

on:
  push:
    branches:
      - 'deploy'

env:
  APP_NAME: sneakyproject-client


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.AMINE_DOCKERHUB_USERNAME }}
          password: ${{ secrets.AMINE_DOCKERHUB_TOKEN }}
      - name: Build and push with commit SHA as tag
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.AMINE_DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:${{ github.sha }}
      - name: Build and push with latest tag
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.AMINE_DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:latest
